### ISSUE TITLE
Firefox Binary?

### ISSUE THREAD

**Issue by Qoyyuum** [SubhrajitPrusty/unsplash-download#7]
```
PS D:\MS1\Documents\unsplash-download> python .\unsplash.py car
Downloading images for car...
Traceback (most recent call last):
  File ".\unsplash.py", line 14, in <module>
    with Browser("firefox",headless=True) as browser:
  File "C:\Users\MS1\.virtualenvs\unsplash-download-F1Te_n-7\lib\site-packages\splinter\browser.py", line 64, in Browser
    return driver(*args, **kwargs)
  File "C:\Users\MS1\.virtualenvs\unsplash-download-F1Te_n-7\lib\site-packages\splinter\driver\webdriver\firefox.py", line 66, in __init__
    binary = FirefoxBinary()
  File "C:\Users\MS1\.virtualenvs\unsplash-download-F1Te_n-7\lib\site-packages\selenium\webdriver\firefox\firefox_binary.py", line 50, in __init__
    "Failed to find firefox binary. You can set it by specifying "
selenium.common.exceptions.WebDriverException: Message: Failed to find firefox binary. You can set it by specifying the path to 'firefox_binary':

from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

binary = FirefoxBinary('/path/to/binary')
driver = webdriver.Firefox(firefox_binary=binary)
```

Not sure if it matters but I have FireFox Developer Edition installed.

**Comment by SubhrajitPrusty** [comment]
`firefox.exe` needs to be in your PATH
